#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  whitelist_external_dirs:
  - /config/camera_snapshot
  packages: !include_dir_named packages

frontend:
  themes: !include themes.yaml

webhook:
 
zigbee2mqtt_networkmap:
  #topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'  

hacs:
  token: !secret hacs

config:

system_health:

#http:
  #api_password: !secret api_password

updater:
discovery:

conversation:
history:
logbook:
map:
sun:

recorder:
  db_url: !secret mariadb_url
  purge_interval: 1
  purge_keep_days: 7

#lovelace:
 #mode: yaml

#################################################################
## Components
#################################################################

nest:
    client_id: !secret nest_client_id
    client_secret: !secret nest_secret

media_player:
        platform: kodi
        host: 192.168.86.39
        port: 80

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

google:
   client_id: !secret google_id
   client_secret: !secret google_secret

hue:
  bridges:
     - host: 192.168.86.46
       allow_unreachable: true
       allow_hue_groups: false

ffmpeg:

stream:

mqtt:
 broker: 192.168.86.27 # This will have to be your mqtt broker
 discovery: true
 discovery_prefix: homeassistant
 username: !secret mqtt_username
 password: !secret mqtt_password
 birth_message:
   topic: 'hass/status'
   payload: 'online'
 will_message:
   topic: 'hass/status'
   payload: 'offline' 

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat

  - name: telegram_chris
    platform: telegram
    chat_id: !secret telegram_chris_chat

telegram_bot:
    platform: polling
    api_key: !secret telegram_api
    parse_mode: html
    allowed_chat_ids:
        - !secret telegram_chat
        - !secret telegram_chris_chat
        - !secret telegram_aimee_chat

pi_hole:
    host: 192.168.86.95
    verify_ssl: false     

influxdb:
  host: 192.168.86.6

remote:
  - platform: harmony
    name: Front room
    host: 192.168.86.30

nzbget:
  host: 192.168.86.20
  username: !secret nzbget_username
  password: !secret nzbget_password

tado:
  username: !secret tado_user
  password: !secret tado_password  

<<<<<<< HEAD
tplink:
=======
#tplink:
>>>>>>> 18b6d154da0e7cce95a0345b9da92b651db2bb3d
 # discovery: false
  #switch:
   # - host: 192.168.86.50
    #- host: 192.168.86.51
    #- host: 192.168.86.52
    #- host: 192.168.86.53
    #- host: 192.168.86.54
    #- host: 192.168.86.55  
    #- host: 192.168.86.56

weather:
#  - platform: metoffice
  #  api_key: !secret metoffice_api

speedtestdotnet:

badnest:
  issue_token: !secret badnest_token
  cookie: !secret badnest_cookie
  region: eu

climate:
  - platform: badnest
    scan_interval: 10

monkey_patch_nest_camera_event_end_date:

#################################################################
## Includes
#################################################################

cloud: !include cloud.yaml
automation: !include_dir_merge_list automation
sensor: !include sensors.yaml
scene: !include scenes.yaml
group: !include groups.yaml
script: !include scripts.yaml
light: !include light_group.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
rest_command: !include rest_command.yaml
input_select: !include input_select.yaml
camera: !include cameras.yaml
timer: !include timers.yaml
switch: !include switch.yaml
device_tracker: !include device_tracker.yaml
yeelight: !include yeelight.yaml
#googlehome: !include googlehome.yaml