#################################################################
## Audio Notification Automations
#################################################################

        ##########################################################
        ## Welcome Home Audio Notification - Chris
        ##########################################################

- alias: 'Chris is home'
  initial_state: on
  trigger:
    platform: state
    from: 'not_home'
    to: 'home'
    entity_id: group.person_chris

  condition:
    - condition: time
      after: '08:00:00'
      before: '22:00:00'

  action:
    - wait_template: "{{ states.binary_sensor.porch_door.state == 'on' }}"
      timeout: 00:05:00
      continue_on_timeout: 'false'
    - delay: 00:00:01
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.hallway_home
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.hallway_home
      data_template:
        #volume_level: .82
        message: !include random_welcome/chris.yaml


        ##########################################################
        ## Welcome Home Audio Notification - Aimee
        ##########################################################

- alias: 'Aimee is home'
  initial_state: on
  trigger:
    platform: state
    from: 'not_home'
    to: 'home'
    entity_id: group.person_aimee

  condition:
    - condition: time
      after: '08:00:00'
      before: '22:00:00'

  action:
    - wait_template: "{{ states.binary_sensor.porch_door.state == 'on' }}"
      timeout: 00:05:00
      continue_on_timeout: 'false'
    - delay: 00:00:01
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.hallway_home
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.hallway_home
      data_template:
       #volume_level: .82
       message: !include random_welcome/aimee.yaml

        ##########################################################
        ## Welcome Home Audio Notification - Keith
        ##########################################################

- alias: 'Keith has arrived'
  initial_state: on
  trigger:
    platform: state
    from: 'not_home'
    to: 'home'
    entity_id: group.person_keith

  condition:
    - condition: time
      after: '08:00:00'
      before: '22:00:00'

  action:
    - wait_template: "{{ states.binary_sensor.front_door.state == 'on' }}"
      timeout: 00:03:00
      continue_on_timeout: 'false'
    - delay: 00:00:03
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.hallway_home
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.hallway_home
      data_template:
       #volume_level: .82
       message: !include random_welcome/keith.yaml

        ##########################################################
        ## Welcome Home Audio Notification - Charlotte
        ##########################################################

- alias: 'Charlotte is home'
  initial_state: on
  trigger:
    platform: state
    from: 'not_home'
    to: 'home'
    entity_id: group.person_charlotte

  condition:
    - condition: time
      after: '08:00:00'
      before: '22:00:00'

  action:
    - wait_template: "{{ states.binary_sensor.porch_door.state == 'on' }}"
      timeout: 00:05:00
      continue_on_timeout: 'false'      
    - delay: 00:00:01
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.hallway_home
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.hallway_home
      data_template:
        ##volume_level: .82
        message: !include random_welcome/charlotte.yaml
